# Project content. Cards use `card` image; case-study pages use the sections below.
DEMO_ONETAP = "https://one-tap-votechain.netlify.app"

projects = [
 dict(id="onetap", card="onetap-card.jpg", kick="One Tap", title="One Tap Voting System", corner="REACT · OTP · BLOCKCHAIN-STYLE LEDGER",
  sum="A secure, browser-based voting platform that combines email OTP authentication, live camera and audio monitoring, and a blockchain-style vote ledger, so a vote can be cast in a single tap and verified afterward.",
  links=[("Live demo", DEMO_ONETAP)],
  built=["One Tap Voting System is a web app for running tamper-evident digital elections. Voters verify their identity with an email OTP, pass a live monitoring check, and cast a vote with one click. Each vote is hashed, assigned a block number, stored as an immutable record, and returned to the voter as downloadable proof. Admins get a separate OTP-protected dashboard to control voting sessions and watch results in real time."],
  features=["Email OTP two-factor authentication for voters, plus a separate admin-only OTP for dashboard access.",
   "One-tap voting: instant vote casting with a single click.",
   "Vote hashing with SHA-256-style transaction hashes and sequential block numbers.",
   "Immutable vote records with a complete audit trail and a blockchain-style timeline log.",
   "Camera and audio monitoring during voting, with an Auto-NOTA trigger when a security breach is detected.",
   "Session-based access control: votes are accepted only inside an active voting period.",
   "Admin dashboard with session management, real-time vote counting, and charts.",
   "Downloadable vote proof as confirmation after casting."],
  workflow=[("User registration","email OTP verification authenticates the voter."),
   ("Profile setup","voter information and verification status are recorded."),
   ("Session check","the system validates that a voting period is active."),
   ("Camera activation","live monitoring starts, with AI-simulated detection."),
   ("One-tap vote","the vote is recorded on a single click."),
   ("Blockchain hash","an immutable transaction hash is generated."),
   ("Vote storage","the encrypted vote is saved to the database."),
   ("Confirmation","the voter sees proof with a download option.")],
  arch_title="Architecture",
  arch=[("01 · Browser","React 18 SPA with Tailwind, Shadcn/UI, and Framer Motion"),("02 · Client logic","React Router, React Query caching, camera/audio monitoring hooks"),
   ("03 · Backend","Base44 BaaS: entity system, RESTful APIs, real-time queries"),("04 · Security","Email OTP, session management, role-based access (admin/user)"),
   ("05 · Ledger","SHA-256-style hashing, sequential block numbers, immutable records")],
  decisions=["Base44's entity system provides structured storage for voters, sessions, and votes, and its real-time queries power live result updates without manual polling. React Query handles data fetching and caching, so the UI stays responsive during active sessions. Votes are never modified after creation: each record carries a hash and block number, which gives a full audit trail and a verifiable timeline. Role-based access separates voter and admin flows, and a security breach during monitoring triggers Auto-NOTA, which enforces the rules without admin intervention.",
   "Note: the blockchain layer and the camera/audio detection are simulated (SHA-256-style hashing and AI-simulated detection), not a distributed ledger or a production ML pipeline."],
  tech=["React 18","Tailwind CSS","Framer Motion","Shadcn/UI","Lucide React","React Query","React Router","Base44 Platform","RESTful APIs","Email OTP","SHA-256 hashing"],
  gallery=[("onetap-splash.jpg","Welcome splash"),("onetap-voter.jpg","Voter profile & status"),("onetap-admin.jpg","Admin election results")]),

 dict(id="studysphere", card="studysphere-card.jpg", kick="StudySphere", title="Collaborative Virtual Study Platform", corner="REACT 19 · FASTAPI · SUPABASE",
  sum="A collaborative virtual study platform where students join study groups, chat in real time, attend live video classes, share materials, and get help from an AI study assistant, all in one browser-based workspace.",
  links=[("Live demo","https://studysphere-tan-rho.vercel.app"),("GitHub","https://github.com/Akshayakumar0207/studysphere")],
  built=["StudySphere is designed as a single place for group learning. Students form or join study groups and talk through group chat. They can also start live video classes and share notes and resources. When they get stuck, they can ask a Gemini-powered AI assistant. The frontend is a React 19 + TypeScript app, and the backend is an async FastAPI service backed by a 24-table Supabase PostgreSQL schema."],
  features=["Group chat for study groups and communities.","Live video classes embedded through Jitsi Meet.","Study material sharing, so groups can upload and access notes and resources.",
   "AI study assistant powered by Google Gemini for doubts, explanations, and revision help.","Relational data model of 24 tables in Supabase PostgreSQL covering users, groups, messages, classes, and materials.",
   "Async FastAPI backend for fast, concurrent API handling.","Deployed on Vercel (frontend) and Render (backend)."],
  workflow=None, arch_title="Architecture",
  arch=[("01 · Browser","React 19 + TypeScript SPA built with Vite"),("02 · API","FastAPI (async) REST backend on Render"),("03 · Data","Supabase PostgreSQL with 24 normalized tables"),
   ("04 · Integrations","Jitsi Meet for live classes, Google Gemini for the AI assistant"),("05 · Deployment","Vercel (frontend) + Render (backend)")],
  decisions=["TypeScript on the frontend catches data-shape errors early across a large feature set. FastAPI's async model keeps chat and AI requests from blocking each other. Supabase PostgreSQL gives a strongly relational schema for users, groups, classes, and materials. Jitsi Meet avoids building video infrastructure from scratch, so live classes work with no custom media servers. Gemini is called from the backend, which keeps the API key off the client. Splitting the deployment lets the frontend and backend scale and redeploy independently."],
  tech=["React 19","TypeScript","Vite","FastAPI","Python (async)","Supabase","PostgreSQL","Jitsi Meet","Google Gemini","Vercel","Render"],
  gallery=[("studysphere-login.jpg","Login"),("studysphere-dashboard.jpg","Dashboard")]),

 dict(id="parkease", card="parkease-card.jpg", kick="ParkEase", title="Real-Time Parking Slot Finder", corner="REACT · FLASK · SOCKET.IO",
  sum="A web platform that helps drivers find and book nearby parking slots while letting space owners list and manage their spaces, with availability updating live across every connected browser.",
  links=[("GitHub","https://github.com/Akshayakumar0207/park-ease-web")],
  built=["ParkEase connects two sides of the parking problem. Drivers search for available slots near their location, see them sorted by distance, and book one. Owners list their parking spaces and manage availability. When a slot is booked or freed, every open browser sees the change instantly through Socket.IO, so nobody books a slot that is already taken."],
  features=["Nearby slot search, with results ranked by distance using the Haversine formula.","Slot booking for users, with live availability.","Owner portal to list and manage parking spaces.",
   "Real-time updates across browsers with Flask-SocketIO, with no manual refresh.","JWT authentication with separate user and owner flows.","MySQL relational storage for users, spaces, slots, and bookings."],
  workflow=[("Sign up / log in","JWT-based authentication for users and owners."),("Search","the user's location is used to find nearby parking spaces."),
   ("Distance ranking","the Haversine formula computes the distance to each space and sorts the results."),("Select a slot","the user views live availability for a space."),
   ("Book","the booking is saved to MySQL and the slot is marked occupied."),("Live broadcast","Socket.IO pushes the update to all connected clients."),
   ("Owner view","owners see bookings and slot status update in real time.")],
  arch_title="Architecture",
  arch=[("01 · Browser","React + Vite SPA"),("02 · API","Flask REST backend with JWT-protected routes"),("03 · Real-time","Flask-SocketIO broadcasting slot changes to all clients"),
   ("04 · Logic","Haversine distance calculation for location-based search"),("05 · Data","MySQL for users, spaces, slots, and bookings")],
  decisions=["Socket.IO was chosen over polling so slot status changes reach every client immediately, which prevents double bookings from stale views. The Haversine formula gives accurate great-circle distances from latitude and longitude, so results rank by real proximity without a paid maps API. JWT keeps the API stateless and lets user and owner roles share one backend. MySQL's relational model suits the clear relationships between owners, spaces, slots, and bookings."],
  tech=["React","Vite","Flask","Flask-SocketIO","Socket.IO","MySQL","JWT","Haversine formula","Python","JavaScript"],
  gallery=[("parkease-signin.jpg","Sign in"),("parkease-find.jpg","Find parking"),("parkease-bookings.jpg","My bookings"),("parkease-rent.jpg","Rent parking")]),

 dict(id="trackit", card="trackit.jpg", kick="TrackIt", title="Real-Time College Bus Tracking Platform", corner="REACT · BASE44 · LIVE GPS",
  sum="A production-ready full-stack transit platform with role-based access for Students, Parents, Drivers, Bus Incharges, and Admins, featuring live GPS tracking, AI-powered route optimization, QR-based boarding validation, SOS alerts, and automated attendance syncing.",
  links=[("Live demo","https://track-it-1b978c5d.base44.app")],
  built=["TrackIt covers the complete campus transit journey: role-based authentication, live bus tracking on an interactive map, stop-wise ETA predictions, QR boarding passes, attendance management, delay alerts, parent notifications, feedback collection, incident reporting, and an administrative control center.",
   "The system is designed as an end-to-end real-time transportation safety platform and highlights AI-driven delay prediction, geolocation-based boarding flows, and proactive parent communication."],
  features=["5-role authentication with role-specific dashboards (Student, Parent, Driver, Bus Incharge, Admin) and persistent sessions.",
   "Real-time GPS tracking via the Geolocation API with live location updates on Leaflet maps for parents and admins.",
   "AI-powered route optimization and delay prediction using LLM-driven analysis of route performance and traffic conditions.",
   "QR-based boarding validation with driver-side scanning and stop-wise boarding checklists.",
   "SOS emergency alerts with parent and admin email notifications and a dedicated SOS response center.",
   "Attendance management with incharge-driven check-in, auto-attendance, history, and CSV/Google Sheets export.",
   "Bus alteration workflow with automatic student and parent email alerts and temporary tracking links.",
   "Parent portal with live child tracking, proximity alerts, leave calendar, and incharge chat.",
   "Admin dashboard with live fleet map, KPIs, attendance/delay charts, feedback analytics, and incident tracker."],
  workflow=None, arch_title="Real-time & data flow",
  arch=[("01 · Client","React + Tailwind CSS + Framer Motion"),("02 · Tracking","Geolocation API + Leaflet maps"),("03 · Backend","Base44 BaaS (entities, auth, functions)"),
   ("04 · AI","LLM route optimization & delay prediction"),("05 · Notifications","Email + in-app + push (PWA)")],
  decisions=["The platform uses Base44 entities for structured persistent data across 17 schemas (Student, Parent, Driver, Bus, Ride, Attendance, Alert, SOSAlert, Incident, Feedback, RouteAnalytics, and more) and LLM integration for actionable route optimization suggestions. The architecture emphasizes real-time subscriptions for live ride updates, PWA installability for native-like mobile use, and a role-isolated UX where each user type sees only the data and actions relevant to them.",
   "Its signature capabilities are AI-powered delay prediction, real-time parent notifications, and a comprehensive QR-based boarding system."],
  tech=["React.js","Vite","Tailwind CSS","Framer Motion","React Router","Recharts","React-Leaflet","Lucide-react","QRCode.react","html5-qrcode","Base44 SDK","LLM integration (InvokeLLM)","PWA","SendEmail integration"],
  gallery=[("trackit-login.jpg","Role login"),("trackit-student.jpg","Student boarding pass"),("trackit-driver.jpg","Driver dashboard")]),

 dict(id="nudge", card="nudge-card.jpg", kick="Nudge", title="Reminders That Take Over Your Screen", corner="REACT · FASTAPI · WEB AUDIO",
  sum="A full-stack reminder platform that works like an alarm clock. When a reminder is due, the screen is taken over by a blinking full-screen alarm with a looping sound, and the reminder's message is read aloud until the user taps Done or Snooze. It includes secure email and Google login, personal profiles, categorized reminders, and a responsive mobile-first interface.",
  links=[("Live demo","https://remainder-app-t6ze.vercel.app/")],
  built=["Most people don't forget tasks because they don't care. They forget because a silent notification is easy to ignore while they're busy. Nudge fixes that by making reminders impossible to miss. Users write a title, a message, a category and a time. At that exact moment the app triggers a loud, blinking alarm screen that reads the message out loud and keeps going until the user responds.",
   "The project covers the full product: authentication, user profiles, a reminders dashboard, a real-time alarm engine in the browser, and a deployed cloud backend."],
  features=["Secure authentication with email and password (JWT sessions) and Google sign-in.","User profiles with an uploadable profile picture.",
   "Reminders with title, description, category (Work, Personal, Health, Study, Other) and a date and time.",
   "A full-screen alarm that blinks between high-contrast colors, loops a beep generated in the browser, and reads the message aloud with text-to-speech.",
   "Snooze for 5 minutes or mark as done, with the screen kept awake while the alarm rings.",
   "Category filters and status tracking (pending, done), so users can see what's upcoming at a glance.",
   "Browser notifications, plus a \"Switch on alarms\" step that satisfies browser autoplay rules.",
   "A responsive layout that works on desktop and phone, installable to the home screen.",
   "Accessibility basics: visible focus states, large touch targets, and a slower blink for users who prefer reduced motion."],
  workflow=None, arch_title="Real-time & data flow",
  arch=[("01 · Client","React + Vite, custom CSS"),("02 · Alarm engine","A timer loop that checks due reminders every second, plus Web Audio, Speech Synthesis and Wake Lock APIs"),
   ("03 · Backend","FastAPI REST API with JWT authentication"),("04 · Database","PostgreSQL on Supabase"),("05 · Hosting","Vercel (frontend) + Render (API)")],
  decisions=[("Browser-side alarm engine","The alarm is triggered on the client rather than from a server job. This keeps the timing accurate to the second and costs nothing to run, and it works even if the API is waking up from sleep."),
   ("No audio files","The alarm tone is generated with the Web Audio API oscillator, so the sound loads instantly with no assets."),
   ("Speech instead of a phone call","My first idea was an automated phone call using a voice service. Since real calls cost money, I redesigned it around free browser text-to-speech and a screen takeover, which delivered the same goal with no per-use cost."),
   ("From SQLite to PostgreSQL","I prototyped on SQLite, then moved to Supabase Postgres when I found Render's free tier wipes its disk on every restart. Profile pictures are stored as validated, size-limited data in the database for the same reason."),
   ("Secure by default","Passwords are hashed with salted PBKDF2, sessions use signed JWTs with expiry, every query is scoped to the logged-in user, and Google tokens are verified on the server."),
   ("Clean deployment","A Vercel rewrite proxies /api calls to the Render backend, so the frontend needs no hardcoded API URLs and avoids CORS issues. Times are stored in UTC and shown in the user's local time."),
   ("Known limit, designed around it","Browsers pause background pages, so the alarm rings while the tab is open. The roadmap covers push notifications and a React Native Android app for lock-screen alarms.")],
  tech=["React.js","Vite","FastAPI","Python","PostgreSQL","Supabase","JWT","Google OAuth","Web Audio API","Speech Synthesis API","Screen Wake Lock API","Notifications API","Vercel","Render"],
  gallery=[("nudge-login.jpg","Login"),("nudge-dashboard.jpg","Reminders dashboard")]),

 dict(id="patisserie", card="patisserie-card.jpg", kick="Pâtisserie Dorée", title="Real-Time Pastry Shop & Ordering Platform", corner="REACT · NODE · TURSO",
  sum="A full-stack e-commerce web application for an artisan pastry shop in Salem, Tamil Nadu, featuring live order tracking, mock payment processing, event catering booking, and a product catalogue of 44 handcrafted pastries across five categories.",
  links=[("Live demo","https://pastry-shop-web.vercel.app/")],
  built=["Pâtisserie Dorée is an end-to-end pastry shop platform that handles the full customer journey: from browsing a categorised menu to placing an order, completing a mock payment, and tracking the delivery in real time. A separate event catering flow lets customers select items, set quantities, and submit booking requests for weddings, birthdays, and corporate events. The backend exposes a REST API built with Node.js and Express, persisted in Turso (LibSQL), and deployed on Render, while the React frontend is served globally via Vercel's CDN."],
  features=["Categorised product catalogue across five categories (Cakes, Cupcakes, Ice Cream, Desserts, and Sweets) with 44 seeded products, descriptions, and pricing.",
   "Cart system with persistent state using localStorage, quantity controls, and live item count in the navbar.",
   "Four-step checkout flow (Cart, Delivery Details, Mock Payment, Confirmation) with order number generation and database persistence.",
   "Mock payment gateway simulating Card, UPI, Net Banking, and Cash on Delivery, with a 95% success simulation and full transaction records.",
   "Real-time order tracking with 8-second polling, a progress stepper across five stages, and a full activity timeline log.",
   "Event catering booking with item selection, quantity controls, and total estimation submitted to the database.",
   "Contact form with all messages stored and retrievable from the database.",
   "Responsive UI with Cormorant Garamond and Outfit typefaces, a deep chocolate and rose-gold design system, glass morphism cards, skeleton loaders, and toast notifications."],
  workflow=[("Browse","customers explore five product categories with search and sort filters."),("Add to Cart","items persist in localStorage across page refreshes."),
   ("Checkout","customer fills delivery details, which are validated and saved to the database."),
   ("Payment","mock payment flow initiates a transaction record, confirms it, and updates order and payment status atomically."),
   ("Track","customer enters their order number; the page polls the backend every 8 seconds and updates the progress stepper and activity log live."),
   ("Event Booking","customers pick items and quantities from the full menu, submit a booking, and receive a booking reference number."),
   ("Contact","messages are stored in the database for the shop owner to read.")],
  arch_title="Architecture",
  arch=[("01 · Browser","React 18 + Vite SPA"),("02 · Routing","React Router v6 with SPA rewrite on Vercel"),("03 · API","Node.js + Express REST backend"),
   ("04 · Database","Turso (LibSQL / SQLite cloud), 8 tables"),("05 · Polling","8-second interval fetch for live order tracking"),
   ("06 · Payment","Mock gateway with transaction lifecycle and atomic DB updates"),("07 · Auth","Stateless, order tracking by order number"),
   ("08 · Images","51 product images served from Vercel CDN via frontend public folder")],
  decisions=[("Turso over MySQL for deployment","Local development used MySQL Workbench, but cloud MySQL free tiers (Supabase, Aiven, Railway, PlanetScale) were either full or had been discontinued. Turso provides a genuinely free, always-on LibSQL database with a mysql2-compatible shim so all existing SQL queries and route files worked without changes."),
   ("Polling over WebSockets for tracking","An 8-second polling interval was chosen over Socket.IO because it requires no persistent connection infrastructure on the free Render tier, is trivially resumable after the server wakes from sleep, and is sufficient for the delivery tracking use case where sub-second latency is not needed."),
   ("Vercel for frontend, Render for backend","Static assets including 51 product images are served from Vercel's global CDN for fast load times. The Node.js API runs on Render's free web service tier. The vercel.json rewrite rule excludes /images/ from the SPA catch-all so image files are served directly."),
   ("Mock payment architecture","The payment flow uses two endpoints: /payments/initiate creates a pending transaction record, and /payments/confirm simulates gateway callback, updates payment status, and atomically updates the order status and inserts a tracking event in a single database transaction.")],
  tech=["React","Vite","React Router","Node.js","Express","Turso (LibSQL)","@libsql/client","Axios","Vercel","Render","JavaScript","CSS Variables","Cormorant Garamond","Outfit"],
  gallery=[("patisserie-home.jpg","Home"),("patisserie-featured.jpg","Featured treats"),("patisserie-shop.jpg","Shop"),("patisserie-events.jpg","Event catering booking"),("patisserie-track.jpg","Order tracking")]),
]

# Freelance section (glass cards). The ebook store also has a full case study page.
freelance = [
 dict(id="ebook-store", free=True, label="Freelance · Own product", card="ebook-card.jpg", kick="Ebook Store", title="Personal Ebook Store: Manual UPI Ebook Selling Platform", corner="REACT · EXPRESS · SUPABASE",
  sum="A full-stack web store where readers buy ebooks by paying through UPI and uploading a screenshot. The admin verifies the payment and releases a private download link. It needs no payment gateway and costs nothing to run on free tiers.",
  links=[("Live demo","https://e-book-sell-web.vercel.app/")],
  built=["The Personal Ebook Store connects two sides of self-publishing. Readers browse ebooks, pay the listed amount through UPI, and upload a payment screenshot. The admin gets each order in a dashboard, checks the screenshot, and approves or rejects it. On approval, the reader gets a private download link by email. I built it so an independent author can sell ebooks directly with no gateway fees, no monthly costs, and no middleman."],
  features=["Ebook catalog with cover images, descriptions, prices, and a book detail page.","Manual UPI checkout where the reader uploads a payment screenshot as proof.",
   "Admin panel at /admin/login to verify payments and approve or reject orders.","Private ebook storage, so files can only be reached through an admin-approved link.",
   "Automatic email delivery of the download link through Gmail and Nodemailer.","JWT authentication for the admin, with a script to create the admin login.",
   "Quote and cover management through public storage buckets.","Free deployment on Vercel, Render, and Supabase."],
  workflow=[("Browse","the reader opens the store and picks an ebook."),("Order","the reader taps Buy now and sees the UPI QR code and the amount."),("Pay","the reader pays through any UPI app."),
   ("Upload proof","the reader submits a payment screenshot with their name and email."),("Store","the screenshot goes to Supabase Storage and the order is saved as pending in Postgres."),
   ("Verify","the admin logs in, reviews the screenshot, and approves or rejects the order."),("Release","on approval, the backend creates a private download link and emails it to the reader."),
   ("Download","the reader downloads the ebook and the order is marked complete.")],
  arch_title="Architecture",
  arch=[("01 · Browser","React + Vite + Tailwind single-page app, hosted on Vercel"),("02 · API","Node.js + Express REST backend with JWT-protected admin routes, hosted on Render"),
   ("03 · Database","Supabase Postgres for books, orders, and admin users"),("04 · Storage","Supabase Storage with buckets covers, quotes, payment-proofs (public) and ebooks (private)"),
   ("05 · Email","Nodemailer sending through Gmail with an App Password")],
  decisions=["Manual UPI verification replaces a payment gateway, which removes transaction fees and merchant approval and keeps the project at ₹0. The ebooks bucket is private, so the files can never be reached by a public URL and are only released through the backend after approval. The backend uses Supabase's service_role key, so database and storage access stays on the server and never reaches the browser. JWT keeps the admin API stateless. Nodemailer with Gmail avoids a paid email service, with a limit of about 500 emails a day. The free tiers have tradeoffs, such as Render sleeping after about 15 minutes idle and Supabase's 1GB storage limit, which are acceptable for a personal store."],
  tech=["React","Vite","Tailwind CSS","Node.js","Express","Supabase","PostgreSQL","Supabase Storage","JWT","Nodemailer","Gmail SMTP","Vercel","Render","JavaScript"],
  gallery=[("ebook-home.jpg","Store home"),("ebook-book.jpg","Book detail"),("ebook-admin.jpg","Admin: manage books")]),
]
ngo = dict(kick="Unity Foundation Salem", title="Full-stack website for an NGO", sum="Developed a full-stack web application for an NGO focused on community development and social welfare. Streamlined operations and improved digital presence.",
  tech=["React.js","Python","REST APIs","Database Design"], link=("Visit website","https://unity-foundation-salem-website.vercel.app"))
